/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-PDF2TEXT.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF2TEXT
 #	author : miyako
 #	2019/10/21
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PDF2TEXT_H
#define PLUGIN_PDF2TEXT_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "C_BLOB.h"

#include "4DPlugin-JSON.h"

#include <assert.h>
#include <stdlib.h>
#include <glib.h>
#include <poppler.h>
#include <poppler-document.h>
#include <poppler-page.h>
#include <cairo.h>
#include <cairo-svg.h>
#include <stdio.h>
#include <string.h>

#include <cstdio>
#include <memory>

#include "ufopen.h"

#include "HtmlOutputDev.h"
#include "SplashOutputDev.h"
#include "splash/SplashBitmap.h"
#include "DateInfo.h"
#include "PDFDocEncoding.h"
#include "PDFDoc.h"
#include "PDFDocFactory.h"
#include "Outline.h"
#include "GlobalParams.h"

typedef PA_long32 method_id_t;

#if defined(_WIN32)
#define snprintf _snprintf
#define vsnprintf _vsnprintf
#define strcasecmp _stricmp
#define strncasecmp _strnicmp
extern "C" BOOL glib_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
extern "C" BOOL gio_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
extern "C" BOOL gobject_DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
#endif

#pragma mark -

static void PDF_Get_XML(PA_PluginParameters params);

#endif /* PLUGIN_PDF2TEXT_H */
